[package]
name = "claws"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
description = "AWS command line tool"
keywords = ["aws", "cli", "s3", "ec2"]
repository = "https://github.com/nicholasbishop/claws"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
rusoto_core = "0.42"
rusoto_ec2 = "0.42"
rusoto_s3 = "0.42"
structopt = "0.3"
